// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdxpvoaqsfloxozifupg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkeHB2b2Fxc2Zsb3hvemlmdXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjU3OTksImV4cCI6MjA2NTcwMTc5OX0.jlmbX0-INQSuq5dl9nqNUhiLRthk63PH26ktpPrTFVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);